### ISSUE TITLE
Marked check-boxes are unchecked in the downloaded PDF.  

### ISSUE THREAD

**Issue by isabeen** [sofittech/palcare-project#233]
![mmm](https://user-images.githubusercontent.com/53593496/70684838-5c412980-1cc9-11ea-819c-8baef0659a04.jpg)

**Comment by qammarkhurshid** [comment]
@isabeen It is working locally. In case the "isChecked" Value is true, I display a small 
checkbox icon (☑). This icon works fine on windows, but does not appear in case of heroku or mac, so this bug is occurring due to the difference in Operating systems -- heroku has linux servers and I am working on windows. I'll solve it tomorrow on mac. Not a logical or functional error, just have to change this icon to something that's compatible with linux servers.
